services:

  agendador-tarefas:
    build: ../agendador-tarefas
    container_name: agendador-tarefas
    ports:
      - "${PORTA_AGENDADOR}:${PORTA_AGENDADOR}"
    environment:
      - SPRING_DATASOURCE_URL_AGENDADOR=${SPRING_DATASOURCE_URL_AGENDADOR}
      - SPRING_DATASOURCE_USERNAME_AGENDADOR=${SPRING_DATASOURCE_USERNAME_AGENDADOR}
      - SPRING_DATASOURCE_PASSWORD_AGENDADOR=${SPRING_DATASOURCE_PASSWORD_AGENDADOR}
      - PORTA_AGENDADOR=${PORTA_AGENDADOR}
      - USUARIO_URL=http://usuario:8080
      - TZ=America/Sao_Paulo
    depends_on:
      - postgres
      - usuario

  bff-agendador-tarefas:
    build: .
    container_name: bff-agendador-tarefas
    ports:
      - "${PORTA_BFF}:${PORTA_BFF}"
    environment:
      - CLIENT_URL_USUARIO=http://usuario:${PORTA_USUARIO}
      - CLIENT_URL_TAREFA=http://agendador-tarefas:${PORTA_AGENDADOR}
      - CLIENT_URL_NOTIFICACAO=http://notificacao:${PORTA_NOTIFICACAO}
      - TZ=America/Sao_Paulo
      - EMAIL_ADMIN=${EMAIL_ADMIN}
      - SENHA_ADMIN=${SENHA_ADMIN}
      - NOME_ADMIN=${NOME_ADMIN}
      - PORTA_BFF=${PORTA_BFF}
    depends_on:
      - usuario
      - agendador-tarefas
      - notificacao

  usuario:
    build: ../usuario
    container_name: usuario
    ports:
      - "${PORTA_USUARIO}:${PORTA_USUARIO}"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_USUARIO}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME_USUARIO}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD_USUARIO}
      - PORTA_USUARIO=${PORTA_USUARIO}
      - TZ=America/Sao_Paulo
      - URL_API_VIACEP=${URL_API_VIACEP}
    depends_on:
      - postgres

  notificacao:
    image: arthurrodriguesr/notificacao:latest
    container_name: notificacao
    ports:
      - "${PORTA_NOTIFICACAO}:${PORTA_NOTIFICACAO}"
    environment:
      - TZ=America/Sao_Paulo
      - KEY_API_CITACAO=${KEY_API_CITACAO}
      - PASSWORD_EMAIL_NOTIFICACAO=${PASSWORD_EMAIL_NOTIFICACAO}
      - USERNAME_EMAIL_NOTIFICACAO=${USERNAME_EMAIL_NOTIFICACAO}
      - PORTA_NOTIFICACAO=${PORTA_NOTIFICACAO}
      - NOME_REMETENTE_EMAIL_NOTIFICACAO=${NOME_REMETENTE_EMAIL_NOTIFICACAO}
      - HOST_EMAIL_NOTIFICACAO=${HOST_EMAIL_NOTIFICACAO}
      - PORTA_EMAIL_NOTIFICACAO=${PORTA_EMAIL_NOTIFICACAO}
      - URL_API_CITACAO=${URL_API_CITACAO}
    depends_on:
      - usuario
      - agendador-tarefas

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${PORTA_POSTGRES}:5432"

networks:
  default:
    driver: bridge