spring:
  application:
    name: bff-agendador-tarefas
  client:
    url:
      usuario: ${CLIENT_URL_USUARIO:http://localhost:8080}
      tarefa: ${CLIENT_URL_TAREFA:http://localhost:8081}
      notificacao: ${CLIENT_URL_NOTIFICACAO:http://localhost:8082}
server:
  port: ${PORTA_BFF}
admin:
  email: ${EMAIL_ADMIN}
  senha: ${SENHA_ADMIN}
  nome: ${NOME_ADMIN}
cron:
  notificacao: "*/10 * * * * *"