spring:
  application:
    name: bff-agendador-tarefas
  client:
    url:
      usuario: http://localhost:8080
      tarefa: http://localhost:8081
      notificacao: http://localhost:8082
server:
  port: 8083
admin:
  email: admin@gmail.com
  senha: adminapp1234
cron:
  notificacao: "0 */5 * * * *"